### PR TITLE
Strict Version of geckodriver

### PR DESCRIPTION
**Pull request by ghost**
usage of StrictVersion on geckodriver truncates '0.21.0' to '0.21' and download fails

### CODE REVIEW

**Comment by r-roos** [comment]
@lucianopuccio confirmed this issue exists

INFO updating geckodriver
ERROR there was a 404 error trying to reach https://github.com/mozilla/geckodriver/releases/download/v0.21/geckodriver-v0.21-macos.tar.gz

**Comment by ghost** [comment]
@lucianopuccio could you please look at this ? thx

**Comment by eirenik0** [comment]
It fails on travisci with next error:
```
INFO got chromedriver_2.43
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/webdriver_manager/webdriver/geckodriver.py", line 42, in get_latest_remote_version
    latest_version = latest_version.replace('v', '')
AttributeError: 'NoneType' object has no attribute 'replace'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/bin/webdriver-manager", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/webdriver_manager/main.py", line 32, in main
    update(driver_name, outputdir, version=requested_version)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/webdriver_manager/__init__.py", line 22, in update
    elif driver.is_remote_higher_than_local():
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/webdriver_manager/webdriver/basedriver.py", line 54, in is_remote_higher_than_local
    latest_remote = self.get_latest_remote_version(strict=True)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/webdriver_manager/webdriver/geckodriver.py", line 45, in get_latest_remote_version
    raise Exception('Could not get latest remote version for geckodriver')
Exception: Could not get latest remote version for geckodriver
```

@lucianopuccio are you planning to fix this issue?

**Comment by luciano-renzi** [comment]
my apologies it took me so long to review this.

**Pull request merged**
